/**
 * dinput8.dll Proxy for FIFA 17 SSL Bypass
 * 
 * NEW APPROACH: Hook the ProtoSSL CA certificate loading function.
 * When the game calls SetCACert to install EA's CA certificate,
 * we replace it with our own CA certificate. This way ProtoSSL's
 * own verification code runs normally and passes because our
 * server cert IS signed by our CA.
 * 
 * We also search for the CA cert data in memory and replace it directly.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>

struct IUnknown;
typedef IUnknown* LPUNKNOWN;

// ============================================================
// DirectInput8 forwarding
// ============================================================

typedef HRESULT(WINAPI* DirectInput8Create_t)(HINSTANCE, DWORD, REFIID, LPVOID*, LPUNKNOWN);
typedef HRESULT(WINAPI* DllCanUnloadNow_t)(void);
typedef HRESULT(WINAPI* DllGetClassObject_t)(REFCLSID, REFIID, LPVOID*);
typedef HRESULT(WINAPI* DllRegisterServer_t)(void);
typedef HRESULT(WINAPI* DllUnregisterServer_t)(void);

static HMODULE g_realDinput8 = NULL;
static DirectInput8Create_t g_realDirectInput8Create = NULL;

static void LoadRealDinput8() {
    if (g_realDinput8) return;
    char systemDir[MAX_PATH];
    GetSystemDirectoryA(systemDir, MAX_PATH);
    strcat_s(systemDir, "\\dinput8.dll");
    g_realDinput8 = LoadLibraryA(systemDir);
    if (g_realDinput8) {
        g_realDirectInput8Create = (DirectInput8Create_t)GetProcAddress(g_realDinput8, "DirectInput8Create");
    }
}

extern "C" {
    __declspec(dllexport) HRESULT WINAPI DirectInput8Create(
        HINSTANCE hinst, DWORD dwVersion, REFIID riidltf, LPVOID* ppvOut, LPUNKNOWN punkOuter) {
        LoadRealDinput8();
        if (g_realDirectInput8Create)
            return g_realDirectInput8Create(hinst, dwVersion, riidltf, ppvOut, punkOuter);
        return E_FAIL;
    }
    __declspec(dllexport) HRESULT WINAPI DllCanUnloadNow(void) {
        LoadRealDinput8();
        auto fn = (DllCanUnloadNow_t)GetProcAddress(g_realDinput8, "DllCanUnloadNow");
        return fn ? fn() : S_FALSE;
    }
    __declspec(dllexport) HRESULT WINAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv) {
        LoadRealDinput8();
        auto fn = (DllGetClassObject_t)GetProcAddress(g_realDinput8, "DllGetClassObject");
        return fn ? fn(rclsid, riid, ppv) : E_FAIL;
    }
    __declspec(dllexport) HRESULT WINAPI DllRegisterServer(void) {
        LoadRealDinput8();
        auto fn = (DllRegisterServer_t)GetProcAddress(g_realDinput8, "DllRegisterServer");
        return fn ? fn() : E_FAIL;
    }
    __declspec(dllexport) HRESULT WINAPI DllUnregisterServer(void) {
        LoadRealDinput8();
        auto fn = (DllUnregisterServer_t)GetProcAddress(g_realDinput8, "DllUnregisterServer");
        return fn ? fn() : E_FAIL;
    }
}

// ============================================================
// Logging
// ============================================================

static FILE* g_logFile = NULL;
static void Log(const char* fmt, ...) {
    if (!g_logFile) g_logFile = fopen("fifa17_ssl_bypass.log", "a");
    if (g_logFile) {
        va_list args;
        va_start(args, fmt);
        vfprintf(g_logFile, fmt, args);
        va_end(args);
        fprintf(g_logFile, "\n");
        fflush(g_logFile);
    }
}

// ============================================================
// Pattern scanning
// ============================================================

static BYTE* FindPattern(BYTE* start, SIZE_T size, const BYTE* pattern, SIZE_T patternLen) {
    for (SIZE_T i = 0; i <= size - patternLen; i++) {
        if (memcmp(start + i, pattern, patternLen) == 0)
            return start + i;
    }
    return NULL;
}

// ============================================================
// Our CA certificate (DER format)
// Generated by setup-certs.sh, matches the server cert
// ============================================================

// Our CA cert - 804 bytes DER format
static const BYTE g_ourCACert[] = {
  0x30, 0x82, 0x03, 0x20, 0x30, 0x82, 0x02, 0x89, 0xa0, 0x03, 0x02, 0x01,
  0x02, 0x02, 0x14, 0x36, 0x1e, 0x75, 0xc6, 0x60, 0x20, 0xd4, 0x6f, 0x4c,
  0x0f, 0xb0, 0x26, 0x1e, 0x5d, 0xe1, 0x50, 0xcc, 0x05, 0x61, 0x5a, 0x30,
  0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x04,
  0x05, 0x00, 0x30, 0x81, 0xa0, 0x31, 0x20, 0x30, 0x1e, 0x06, 0x03, 0x55,
  0x04, 0x0b, 0x0c, 0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x20, 0x54,
  0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x20, 0x47, 0x72,
  0x6f, 0x75, 0x70, 0x31, 0x1e, 0x30, 0x1c, 0x06, 0x03, 0x55, 0x04, 0x0a,
  0x0c, 0x15, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x63,
  0x20, 0x41, 0x72, 0x74, 0x73, 0x2c, 0x20, 0x49, 0x6e, 0x63, 0x2e, 0x31,
  0x15, 0x30, 0x13, 0x06, 0x03, 0x55, 0x04, 0x07, 0x0c, 0x0c, 0x52, 0x65,
  0x64, 0x77, 0x6f, 0x6f, 0x64, 0x20, 0x43, 0x69, 0x74, 0x79, 0x31, 0x13,
  0x30, 0x11, 0x06, 0x03, 0x55, 0x04, 0x08, 0x0c, 0x0a, 0x43, 0x61, 0x6c,
  0x69, 0x66, 0x6f, 0x72, 0x6e, 0x69, 0x61, 0x31, 0x0b, 0x30, 0x09, 0x06,
  0x03, 0x55, 0x04, 0x06, 0x13, 0x02, 0x55, 0x53, 0x31, 0x23, 0x30, 0x21,
  0x06, 0x03, 0x55, 0x04, 0x03, 0x0c, 0x1a, 0x4f, 0x54, 0x47, 0x33, 0x20,
  0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x20,
  0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x30, 0x20, 0x17,
  0x0d, 0x32, 0x36, 0x30, 0x34, 0x31, 0x30, 0x31, 0x32, 0x30, 0x37, 0x35,
  0x36, 0x5a, 0x18, 0x0f, 0x32, 0x31, 0x30, 0x33, 0x30, 0x34, 0x31, 0x31,
  0x31, 0x32, 0x30, 0x37, 0x35, 0x36, 0x5a, 0x30, 0x81, 0xa0, 0x31, 0x20,
  0x30, 0x1e, 0x06, 0x03, 0x55, 0x04, 0x0b, 0x0c, 0x17, 0x4f, 0x6e, 0x6c,
  0x69, 0x6e, 0x65, 0x20, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f,
  0x67, 0x79, 0x20, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x31, 0x1e, 0x30, 0x1c,
  0x06, 0x03, 0x55, 0x04, 0x0a, 0x0c, 0x15, 0x45, 0x6c, 0x65, 0x63, 0x74,
  0x72, 0x6f, 0x6e, 0x69, 0x63, 0x20, 0x41, 0x72, 0x74, 0x73, 0x2c, 0x20,
  0x49, 0x6e, 0x63, 0x2e, 0x31, 0x15, 0x30, 0x13, 0x06, 0x03, 0x55, 0x04,
  0x07, 0x0c, 0x0c, 0x52, 0x65, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x20, 0x43,
  0x69, 0x74, 0x79, 0x31, 0x13, 0x30, 0x11, 0x06, 0x03, 0x55, 0x04, 0x08,
  0x0c, 0x0a, 0x43, 0x61, 0x6c, 0x69, 0x66, 0x6f, 0x72, 0x6e, 0x69, 0x61,
  0x31, 0x0b, 0x30, 0x09, 0x06, 0x03, 0x55, 0x04, 0x06, 0x13, 0x02, 0x55,
  0x53, 0x31, 0x23, 0x30, 0x21, 0x06, 0x03, 0x55, 0x04, 0x03, 0x0c, 0x1a,
  0x4f, 0x54, 0x47, 0x33, 0x20, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
  0x63, 0x61, 0x74, 0x65, 0x20, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
  0x74, 0x79, 0x30, 0x81, 0x9f, 0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48,
  0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00, 0x03, 0x81, 0x8d, 0x00,
  0x30, 0x81, 0x89, 0x02, 0x81, 0x81, 0x00, 0xe3, 0x5f, 0xe0, 0x5d, 0x64,
  0xda, 0xb4, 0xab, 0xf4, 0x16, 0xb6, 0x5e, 0x9b, 0x6e, 0x31, 0x61, 0x3c,
  0x6c, 0xb8, 0x1f, 0x18, 0x02, 0x00, 0x7b, 0xc5, 0xa7, 0xb2, 0xb2, 0xf7,
  0x20, 0x4d, 0x23, 0x4d, 0xa6, 0xca, 0xf5, 0xa0, 0x30, 0x7c, 0x4a, 0x4b,
  0x11, 0xb3, 0x1e, 0x73, 0xa6, 0x20, 0x1a, 0x58, 0x7d, 0xb2, 0x6c, 0x6e,
  0xf9, 0x0b, 0xaa, 0x8a, 0xba, 0x83, 0xe1, 0x9e, 0xd6, 0x6b, 0x28, 0x36,
  0xd3, 0x1c, 0x0b, 0x4b, 0x34, 0x3a, 0x30, 0xa6, 0xda, 0x3a, 0x41, 0x76,
  0xbc, 0xf7, 0x07, 0x32, 0x3f, 0xb0, 0x36, 0x03, 0x29, 0x81, 0x6f, 0x24,
  0x72, 0x34, 0xe3, 0x5c, 0x53, 0x9b, 0xba, 0x83, 0x23, 0xb7, 0xe2, 0xef,
  0x00, 0x66, 0x64, 0x1e, 0x18, 0x0f, 0x48, 0xc8, 0x21, 0xbe, 0x0c, 0xd5,
  0x66, 0xca, 0x2f, 0x75, 0x00, 0x15, 0xb2, 0x32, 0x3d, 0xc5, 0x03, 0xfc,
  0xbf, 0xe9, 0x45, 0x02, 0x03, 0x01, 0x00, 0x01, 0xa3, 0x53, 0x30, 0x51,
  0x30, 0x1d, 0x06, 0x03, 0x55, 0x1d, 0x0e, 0x04, 0x16, 0x04, 0x14, 0x8e,
  0x51, 0xa4, 0x40, 0xfb, 0x32, 0x35, 0x13, 0x0f, 0x46, 0x4a, 0xf9, 0xc2,
  0xe4, 0xd6, 0xab, 0xbf, 0x1f, 0x91, 0xa0, 0x30, 0x1f, 0x06, 0x03, 0x55,
  0x1d, 0x23, 0x04, 0x18, 0x30, 0x16, 0x80, 0x14, 0x8e, 0x51, 0xa4, 0x40,
  0xfb, 0x32, 0x35, 0x13, 0x0f, 0x46, 0x4a, 0xf9, 0xc2, 0xe4, 0xd6, 0xab,
  0xbf, 0x1f, 0x91, 0xa0, 0x30, 0x0f, 0x06, 0x03, 0x55, 0x1d, 0x13, 0x01,
  0x01, 0xff, 0x04, 0x05, 0x30, 0x03, 0x01, 0x01, 0xff, 0x30, 0x0d, 0x06,
  0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x04, 0x05, 0x00,
  0x03, 0x81, 0x81, 0x00, 0x50, 0x5f, 0xe3, 0x26, 0xbb, 0x53, 0x3d, 0xd3,
  0xcd, 0xfb, 0x20, 0xf5, 0xd0, 0xe4, 0x1f, 0x72, 0xb2, 0xf7, 0xc4, 0x1c,
  0xc8, 0xc0, 0x13, 0xf8, 0x73, 0x44, 0x66, 0x70, 0x57, 0x55, 0xf8, 0xa8,
  0x55, 0x50, 0x68, 0x84, 0xdf, 0x74, 0x94, 0x7e, 0xfc, 0x88, 0x97, 0xae,
  0x01, 0x94, 0x6e, 0x6a, 0x82, 0x7f, 0x8f, 0x0d, 0xb1, 0xa2, 0x12, 0x56,
  0x4d, 0xdb, 0x8d, 0x67, 0x98, 0xd7, 0x0b, 0x6f, 0x79, 0xed, 0x99, 0xbf,
  0x68, 0x22, 0x3c, 0xee, 0xf2, 0xb7, 0x41, 0x31, 0xf1, 0x3f, 0x78, 0xf1,
  0x1e, 0xaf, 0xd3, 0x35, 0x36, 0x75, 0xa6, 0x41, 0x27, 0x5e, 0x5f, 0x7f,
  0xae, 0xb5, 0x4c, 0x9c, 0xfb, 0xe1, 0x44, 0x47, 0xb7, 0x13, 0x1b, 0xf3,
  0x5a, 0x5d, 0xe9, 0xc1, 0xd8, 0x65, 0xe0, 0xfb, 0x47, 0xc5, 0x99, 0x6f,
  0x7a, 0xcc, 0xba, 0xd2, 0xe5, 0x38, 0x0e, 0x56, 0xb2, 0x82, 0x97, 0x21
};
static const SIZE_T g_ourCACertLen = 804;

// ============================================================
// SSL Bypass - Replace EA's CA cert with ours
// ============================================================

static void PatchSSL() {
    Log("=== FIFA 17 SSL Bypass DLL (CA Replacement) ===");
    
    HMODULE gameModule = GetModuleHandleA("FIFA17.exe");
    if (!gameModule) { Log("ERROR: FIFA17.exe not found"); return; }
    
    BYTE* baseAddr = (BYTE*)gameModule;
    IMAGE_DOS_HEADER* dosHeader = (IMAGE_DOS_HEADER*)baseAddr;
    IMAGE_NT_HEADERS* ntHeaders = (IMAGE_NT_HEADERS*)(baseAddr + dosHeader->e_lfanew);
    SIZE_T moduleSize = ntHeaders->OptionalHeader.SizeOfImage;
    Log("FIFA17.exe base=0x%p size=0x%llX", baseAddr, (unsigned long long)moduleSize);
    
    // Strategy 1: Find the "installed CA cert" log string and hook the function
    // that calls it. The function receives (certPtr, certSize) and we replace
    // the cert data with ours.
    
    // Strategy 2: Search for DER certificate structures in the game's memory.
    // EA's CA cert starts with 0x30 0x82 (ASN.1 SEQUENCE) and contains
    // the issuer "OTG3 Certificate Authority" or similar.
    // We find it and overwrite it with our CA cert.
    
    // Strategy 3: Hook ProtoHttpControl which is used to set the CA cert.
    // The string "installed CA cert" tells us the function succeeded.
    
    // Let's try all strategies:
    
    Log("Waiting for Denuvo decryption (2s)...");
    Sleep(2000);
    
    // === Find the "installed CA cert" string to locate SetCACert function ===
    // This string is in the .srdata section (not encrypted)
    const char* searchStr = "installed CA cert";
    BYTE* strAddr = FindPattern(baseAddr, moduleSize, (const BYTE*)searchStr, strlen(searchStr));
    if (strAddr) {
        Log("Found 'installed CA cert' string at +0x%llX", (unsigned long long)(strAddr - baseAddr));
        
        // Now search for code that references this string address
        // In x64, LEA uses RIP-relative: 48 8D xx [offset32]
        // The offset = strAddr - (leaAddr + 7)
        Log("Searching for code references to this string...");
        for (SIZE_T i = 0; i < moduleSize - 7; i++) {
            // Look for LEA with RIP-relative addressing
            if ((baseAddr[i] == 0x48 || baseAddr[i] == 0x4C) && baseAddr[i+1] == 0x8D) {
                BYTE modrm = baseAddr[i+2];
                if ((modrm & 0xC7) == 0x05 || (modrm & 0xC7) == 0x0D || 
                    (modrm & 0xC7) == 0x15 || (modrm & 0xC7) == 0x1D ||
                    (modrm & 0xC7) == 0x25 || (modrm & 0xC7) == 0x2D ||
                    (modrm & 0xC7) == 0x35 || (modrm & 0xC7) == 0x3D) {
                    int32_t offset = *(int32_t*)(baseAddr + i + 3);
                    BYTE* target = baseAddr + i + 7 + offset;
                    if (target == strAddr) {
                        Log("  LEA reference at +0x%llX", (unsigned long long)i);
                        // Dump surrounding code
                        char hex[512] = {0};
                        SIZE_T start = (i > 64) ? i - 64 : 0;
                        for (SIZE_T j = 0; j < 128 && start + j < moduleSize; j++) {
                            sprintf(hex + j * 3, "%02X ", baseAddr[start + j]);
                        }
                        Log("  Code context: %s", hex);
                    }
                }
            }
        }
    } else {
        Log("'installed CA cert' string NOT FOUND in module");
    }
    
    // === Also scan for DER certs with relaxed criteria ===
    Log("Scanning for DER certificates (relaxed)...");
    int certsFound = 0;
    
    for (SIZE_T i = 0; i < moduleSize - 10; i++) {
        if (baseAddr[i] != 0x30 || baseAddr[i+1] != 0x82) continue;
        uint16_t outerLen = (baseAddr[i+2] << 8) | baseAddr[i+3];
        if (outerLen < 200 || outerLen > 2000) continue;
        SIZE_T certSize = outerLen + 4;
        if (i + certSize > moduleSize) continue;
        if (baseAddr[i+4] != 0x30) continue;
        
        BYTE rsaOid[] = {0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01};
        if (!FindPattern(baseAddr + i, certSize, rsaOid, 8)) continue;
        
        certsFound++;
        // Extract some readable text
        char txt[128] = {0};
        int tp = 0;
        for (SIZE_T j = 0; j < certSize && tp < 120; j++) {
            BYTE b = baseAddr[i+j];
            if (b >= 0x20 && b < 0x7F) txt[tp++] = (char)b;
            else if (tp > 0 && txt[tp-1] != ' ') txt[tp++] = ' ';
        }
        Log("  Cert #%d at +0x%llX size=%llu: %.100s", certsFound, (unsigned long long)i, (unsigned long long)certSize, txt);
        if (certsFound >= 20) break;
    }
    // === Also scan HEAP memory for DER certs ===
    // The CA cert might be allocated on the heap, not in the module
    Log("Scanning process heap for DER certificates...");
    int heapCerts = 0;
    
    MEMORY_BASIC_INFORMATION mbi;
    BYTE* addr = NULL;
    while (VirtualQuery(addr, &mbi, sizeof(mbi))) {
        if (mbi.State == MEM_COMMIT && (mbi.Protect & (PAGE_READWRITE | PAGE_READONLY | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE))) {
            // Skip the game module (already scanned)
            if ((BYTE*)mbi.BaseAddress >= baseAddr && (BYTE*)mbi.BaseAddress < baseAddr + moduleSize) {
                addr = (BYTE*)mbi.BaseAddress + mbi.RegionSize;
                continue;
            }
            
            BYTE* regionBase = (BYTE*)mbi.BaseAddress;
            SIZE_T regionSize = mbi.RegionSize;
            
            __try {
                for (SIZE_T i = 0; i < regionSize - 10; i++) {
                    if (regionBase[i] != 0x30 || regionBase[i+1] != 0x82) continue;
                    uint16_t outerLen = (regionBase[i+2] << 8) | regionBase[i+3];
                    if (outerLen < 200 || outerLen > 2000) continue;
                    SIZE_T certSize = outerLen + 4;
                    if (i + certSize > regionSize) continue;
                    if (regionBase[i+4] != 0x30) continue;
                    
                    BYTE rsaOid[] = {0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01};
                    if (!FindPattern(regionBase + i, certSize, rsaOid, 8)) continue;
                    
                    heapCerts++;
                    char txt[128] = {0};
                    int tp = 0;
                    for (SIZE_T j = 0; j < certSize && tp < 120; j++) {
                        BYTE b = regionBase[i+j];
                        if (b >= 0x20 && b < 0x7F) txt[tp++] = (char)b;
                        else if (tp > 0 && txt[tp-1] != ' ') txt[tp++] = ' ';
                    }
                    
                    BYTE caTrue[] = {0x30, 0x03, 0x01, 0x01, 0xFF};
                    BYTE* caMatch = FindPattern(regionBase + i, certSize, caTrue, 5);
                    
                    Log("  Heap cert #%d at 0x%p size=%llu CA=%s: %.80s",
                        heapCerts, regionBase + i, (unsigned long long)certSize,
                        caMatch ? "YES" : "no", txt);
                    
                    if (caMatch && certSize >= g_ourCACertLen) {
                        Log("  -> REPLACING CA cert at 0x%p!", regionBase + i);
                        DWORD oldProt;
                        if (VirtualProtect(regionBase + i, certSize, PAGE_READWRITE, &oldProt)) {
                            memcpy(regionBase + i, g_ourCACert, g_ourCACertLen);
                            if (certSize > g_ourCACertLen)
                                memset(regionBase + i + g_ourCACertLen, 0, certSize - g_ourCACertLen);
                            VirtualProtect(regionBase + i, certSize, oldProt, &oldProt);
                            Log("  -> REPLACED!");
                        }
                    }
                    
                    i += certSize - 1;
                    if (heapCerts >= 30) break;
                }
            } __except(EXCEPTION_EXECUTE_HANDLER) {
                // Skip unreadable regions
            }
        }
        addr = (BYTE*)mbi.BaseAddress + mbi.RegionSize;
        if (heapCerts >= 30) break;
    }
    Log("Found %d heap DER certs", heapCerts);
    
    // === Strategy 2: Also patch the error handler (keep from previous approach) ===
    BYTE errorPattern[] = { 
        0x40, 0x38, 0xBB, 0x86, 0x03, 0x00, 0x00,
        0x74, 0x13,
        0xBA, 0x0F, 0xA2, 0xFF, 0xE7,
        0x8D, 0x92, 0xF3, 0x5D, 0x00, 0x18
    };
    BYTE* errorMatch = FindPattern(baseAddr, moduleSize, errorPattern, 20);
    if (errorMatch) {
        Log("Found error handler at +0x%llX, patching JE->JMP", (unsigned long long)(errorMatch - baseAddr));
        DWORD oldProtect;
        VirtualProtect(errorMatch + 7, 2, PAGE_EXECUTE_READWRITE, &oldProtect);
        errorMatch[7] = 0xEB; // JE -> JMP
        VirtualProtect(errorMatch + 7, 2, oldProtect, &oldProtect);
        
        // Also patch disconnect function
        BYTE* callAddr = errorMatch + 20;
        if (callAddr[0] == 0xE8) {
            int32_t callOffset = *(int32_t*)(callAddr + 1);
            BYTE* targetFunc = callAddr + 5 + callOffset;
            VirtualProtect(targetFunc, 3, PAGE_EXECUTE_READWRITE, &oldProtect);
            targetFunc[0] = 0x31; targetFunc[1] = 0xC0; targetFunc[2] = 0xC3;
            VirtualProtect(targetFunc, 3, oldProtect, &oldProtect);
            Log("Patched disconnect func to return 0");
        }
    }
    
    Log("All patches applied!");
}

// ============================================================
// DLL Entry Point
// ============================================================

static DWORD WINAPI PatchThread(LPVOID) {
    // Start quickly - the CA cert might be loaded early
    Sleep(2000);
    PatchSSL();
    
    // Keep re-scanning every 2 seconds for 60 seconds
    // to catch certs loaded after our initial scan
    for (int pass = 0; pass < 30; pass++) {
        Sleep(2000);
        MEMORY_BASIC_INFORMATION mbi;
        BYTE* scanAddr = NULL;
        int replaced = 0;
        while (VirtualQuery(scanAddr, &mbi, sizeof(mbi))) {
            if (mbi.State == MEM_COMMIT && 
                (mbi.Protect & (PAGE_READWRITE | PAGE_READONLY | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE))) {
                BYTE* base = (BYTE*)mbi.BaseAddress;
                SIZE_T size = mbi.RegionSize;
                __try {
                    for (SIZE_T j = 0; j < size - 10; j++) {
                        if (base[j] != 0x30 || base[j+1] != 0x82) continue;
                        uint16_t len = (base[j+2] << 8) | base[j+3];
                        if (len < 200 || len > 2000) continue;
                        SIZE_T cs = len + 4;
                        if (j + cs > size) continue;
                        BYTE ca[] = {0x30, 0x03, 0x01, 0x01, 0xFF};
                        if (!FindPattern(base + j, cs, ca, 5)) continue;
                        if (memcmp(base + j, g_ourCACert, 20) == 0) { j += cs - 1; continue; }
                        BYTE oid[] = {0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01};
                        if (!FindPattern(base + j, cs, oid, 8)) continue;
                        DWORD op;
                        if (VirtualProtect(base + j, cs, PAGE_READWRITE, &op)) {
                            SIZE_T copyLen = (cs < g_ourCACertLen) ? cs : g_ourCACertLen;
                            memcpy(base + j, g_ourCACert, copyLen);
                            VirtualProtect(base + j, cs, op, &op);
                            replaced++;
                            Log("Pass %d: replaced CA cert at 0x%p size=%llu", pass, base + j, (unsigned long long)cs);
                        }
                        j += cs - 1;
                    }
                } __except(EXCEPTION_EXECUTE_HANDLER) {}
            }
            scanAddr = (BYTE*)mbi.BaseAddress + mbi.RegionSize;
        }
    }
    return 0;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID reserved) {
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hModule);
        LoadRealDinput8();
        CreateThread(NULL, 0, PatchThread, NULL, 0, NULL);
    }
    else if (reason == DLL_PROCESS_DETACH) {
        if (g_realDinput8) FreeLibrary(g_realDinput8);
        if (g_logFile) fclose(g_logFile);
    }
    return TRUE;
}
